[2023-11-30T15:35:27.954+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_users.extract_data scheduled__2023-10-18T00:00:00+00:00 [queued]>
[2023-11-30T15:35:28.217+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_users.extract_data scheduled__2023-10-18T00:00:00+00:00 [queued]>
[2023-11-30T15:35:28.217+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-30T15:35:28.864+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract_data> on 2023-10-18 00:00:00+00:00
[2023-11-30T15:35:29.231+0000] {standard_task_runner.py:57} INFO - Started process 238 to run task
[2023-11-30T15:35:29.248+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_users', 'extract_data', 'scheduled__2023-10-18T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/ETL_users.py', '--cfg-path', '/tmp/tmpcl_ie84j']
[2023-11-30T15:35:29.249+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask extract_data
[2023-11-30T15:37:15.381+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task extract_data ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 238)
[2023-11-30T15:42:08.883+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T15:42:09.913+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
